// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4uz3yh9KFAx4bbG3gT3ZbQYTzlLM_nSE',
    appId: '1:848359052042:web:fab688cf2902a8edae20f3',
    messagingSenderId: '848359052042',
    projectId: 'ulist-f02bb',
    authDomain: 'ulist-f02bb.firebaseapp.com',
    storageBucket: 'ulist-f02bb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbO42erpGnDmzpRRWo8VyX1Xd0KYid8-o',
    appId: '1:848359052042:android:a1126e26034b526aae20f3',
    messagingSenderId: '848359052042',
    projectId: 'ulist-f02bb',
    storageBucket: 'ulist-f02bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0712Gs-GRSUL-i98kHh0zBCUhg06eISQ',
    appId: '1:848359052042:ios:0e0a35d9e470f772ae20f3',
    messagingSenderId: '848359052042',
    projectId: 'ulist-f02bb',
    storageBucket: 'ulist-f02bb.appspot.com',
    iosBundleId: 'ulisttesteios.example.app',
  );
}
